export enum PAYMENT_TRANSACTION_STATUS {
  INCOMPLETE = 'INCOMPLETE',
  UN_CAPTURED = 'UN_CAPTURED',
  SUCCESS = 'SUCCESS',
  REFUND = 'REFUND',
  CANCELLED = 'CANCELLED',
}

export enum PAYMENT_TRANSACTION_TYPE {
  BOOKING = 'BOOKING',
  DUE = 'DUE',
  DELIVERY = 'DELIVERY',
}

export enum CARD_FOR {
  VELET = 'VELET',
  DELIVERY = 'DELIVERY',
}
